using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace MyWayApp23.Configuration
{
    public class StandConfiguration : IEntityTypeConfiguration<Stand>
    {

        public void Configure(EntityTypeBuilder<Stand> builder)
        {
            builder.HasData(
                   new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "104", Tipo = "REMOTE" },
                   new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "105", Tipo = "REMOTE" },
                   new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "106", Tipo = "REMOTE" },
                   new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "107", Tipo = "JETBRIDGE" },
                   new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "108", Tipo = "JETBRIDGE" },
                   new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "114", Tipo = "JETBRIDGE" },
                   new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "115", Tipo = "JETBRIDGE" },
                   new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "116", Tipo = "JETBRIDGE" },
                   new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "117", Tipo = "JETBRIDGE" },
                   new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "118", Tipo = "JETBRIDGE" },
                   new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "119", Tipo = "JETBRIDGE" },
                   new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "120", Tipo = "JETBRIDGE" },
                   new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "121", Tipo = "JETBRIDGE" },
                   new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "122", Tipo = "JETBRIDGE" },
                   new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "123", Tipo = "JETBRIDGE" },
                   new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "124", Tipo = "JETBRIDGE" },
                   new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "125", Tipo = "JETBRIDGE" },
                   new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "126", Tipo = "JETBRIDGE" },
                   new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "127", Tipo = "JETBRIDGE" },
                   new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "140", Tipo = "JETBRIDGE" },
                   new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "141", Tipo = "JETBRIDGE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "142", Tipo = "JETBRIDGE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "143", Tipo = "JETBRIDGE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "144", Tipo = "JETBRIDGE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "145", Tipo = "JETBRIDGE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "146", Tipo = "JETBRIDGE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "147", Tipo = "JETBRIDGE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "200", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "201", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "202", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "203", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "204", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "205", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "206", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "207", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "208", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "209", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "221", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "222", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "223", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "224", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "225", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "301", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "302", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "401", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "402", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "403", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "404", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "405", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "411", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "412", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "413", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "414", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "415", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "416", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "421", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "422", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "423", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "424", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "425", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "426", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "500", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "501", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "502", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "503", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "504", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "505", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "506", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "600", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "601", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "603", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "604", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "605", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "606", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "607", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "608", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "609", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "701", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "702", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "703", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "704", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "705", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "706", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "801", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "802", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "803", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "804", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "805", Tipo = "REMOTE" },
                    new Stand { Id = Guid.NewGuid(), Aeroporto = "Lis", Numero = "806", Tipo = "REMOTE" }
            );
        }
    }
}
